package fun.yizhierha.tools.other.service;

import fun.yizhierha.common.base.BaseErrDto;
import fun.yizhierha.common.utils.PageUtils;
import fun.yizhierha.common.utils.Query;
import fun.yizhierha.common.utils.ValidList;
import com.baomidou.mybatisplus.extension.service.IService;
import fun.yizhierha.tools.other.domain.ToolQiniuConfig;
import fun.yizhierha.tools.other.domain.vo.CreateToolQiniuConfigVo;
import fun.yizhierha.tools.other.domain.vo.UpdateToolQiniuConfigVo;
import fun.yizhierha.tools.other.domain.vo.RetrieveToolQiniuConfigVo;

import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.Set;

/** generated by EH-Admin
* @author erha
* @date Sun Jan 08 13:57:58 CST 2023
**/
public interface ToolQiniuConfigService extends IService<ToolQiniuConfig>{

    PageUtils<ToolQiniuConfig> list(RetrieveToolQiniuConfigVo retrieveToolQiniuConfigVo, Query.PageVo pageVo);

    void save(CreateToolQiniuConfigVo createToolQiniuConfigVo);

    void edit(ValidList<UpdateToolQiniuConfigVo> updateToolQiniuConfigVoList, List<BaseErrDto> errDtoList);

    void remove(Set<Long> ids);

    void download(HttpServletResponse response);

    void activeConfig(Long id);

    List<ToolQiniuConfig> getActiveConfig();

}