package fun.yizhierha.operation.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:15:54 CST 2022
**/
@ApiModel(value = "应用管理")
@Data
@TableName(value = "ora_app")
public class OraApp implements Serializable{

    @TableId(value = "app_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "name")
    @ApiModelProperty(value = "应用名称")
    @ExcelExport("应用名称")
    private String name;

    @TableField(value = "upload_path")
    @ApiModelProperty(value = "上传目录")
    @ExcelExport("上传目录")
    private String uploadPath;

    @TableField(value = "deploy_path")
    @ApiModelProperty(value = "部署路径")
    @ExcelExport("部署路径")
    private String deployPath;

    @TableField(value = "backup_path")
    @ApiModelProperty(value = "备份路径")
    @ExcelExport("备份路径")
    private String backupPath;

    @TableField(value = "port")
    @ApiModelProperty(value = "应用端口")
    @ExcelExport("应用端口")
    private Integer port;

    @TableField(value = "start_script")
    @ApiModelProperty(value = "启动脚本")
    @ExcelExport("启动脚本")
    private String startScript;

    @TableField(value = "deploy_script")
    @ApiModelProperty(value = "部署脚本")
    @ExcelExport("部署脚本")
    private String deployScript;

    @TableField(value = "create_by")
    @ApiModelProperty(value = "创建者")
    @ExcelExport("创建者")
    private String createBy;

    @TableField(value = "update_by")
    @ApiModelProperty(value = "更新者")
    @ExcelExport("更新者")
    private String updateBy;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建日期")
    @ExcelExport("创建日期")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    @TableField(value = "project_id")
    @ApiModelProperty(value = "项目ID")
    @ExcelExport("项目ID")
    private Long projectId;


    private static final long serialVersionUID = 1L;

    public static final String COL_APP_ID = "app_id";

    public static final String COL_NAME = "name";

    public static final String COL_UPLOAD_PATH = "upload_path";

    public static final String COL_DEPLOY_PATH = "deploy_path";

    public static final String COL_BACKUP_PATH = "backup_path";

    public static final String COL_PORT = "port";

    public static final String COL_START_SCRIPT = "start_script";

    public static final String COL_DEPLOY_SCRIPT = "deploy_script";

    public static final String COL_CREATE_BY = "create_by";

    public static final String COL_UPDATE_BY = "update_by";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

    public static final String COL_PROJECT_ID = "project_id";


}