package fun.yizhierha.operation.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:55:14 CST 2022
**/
@ApiModel(value = "部署管理")
@Data
@TableName(value = "ora_deploy_history")
public class OraDeployHistory implements Serializable{

    @TableId(value = "history_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "app_name")
    @ApiModelProperty(value = "应用名称")
    @ExcelExport("应用名称")
    private String appName;

    @TableField(value = "deploy_date")
    @ApiModelProperty(value = "部署日期")
    @ExcelExport("部署日期")
    private Timestamp deployDate;

    @TableField(value = "deploy_user")
    @ApiModelProperty(value = "部署用户")
    @ExcelExport("部署用户")
    private String deployUser;

    @TableField(value = "ip")
    @ApiModelProperty(value = "服务器IP")
    @ExcelExport("服务器IP")
    private String ip;

    @TableField(value = "deploy_id")
    @ApiModelProperty(value = "部署编号")
    @ExcelExport("部署编号")
    private Long deployId;

    @TableField(value = "project_id")
    @ApiModelProperty(value = "项目ID")
    @ExcelExport("项目ID")
    private Long projectId;
    @TableField(value = "file_name")
    @ApiModelProperty(value = "文件名称")
    @ExcelExport("文件名称")
    private String fileName;
    private static final long serialVersionUID = 1L;

    public static final String COL_HISTORY_ID = "history_id";

    public static final String COL_APP_NAME = "app_name";

    public static final String COL_DEPLOY_DATE = "deploy_date";

    public static final String COL_DEPLOY_USER = "deploy_user";

    public static final String COL_IP = "ip";

    public static final String COL_DEPLOY_ID = "deploy_id";

    public static final String COL_PROJECT_ID = "project_id";
    public static final String FILE_NAME = "file_name";
}