package fun.yizhierha.operation.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 16:08:00 CST 2022
**/
@ApiModel(value = "部署管理")
@Data
@TableName(value = "ora_database")
public class OraDatabase implements Serializable{

    @TableId(value = "db_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "name")
    @ApiModelProperty(value = "名称")
    @ExcelExport("名称")
    private String name;

    @TableField(value = "jdbc_url")
    @ApiModelProperty(value = "jdbc连接")
    @ExcelExport("jdbc连接")
    private String jdbcUrl;

    @TableField(value = "user_name")
    @ApiModelProperty(value = "账号")
    @ExcelExport("账号")
    private String userName;

    @TableField(value = "pwd")
    @ApiModelProperty(value = "密码")
    @ExcelExport("密码")
    private String pwd;

    @TableField(value = "create_by")
    @ApiModelProperty(value = "创建者")
    @ExcelExport("创建者")
    private String createBy;

    @TableField(value = "update_by")
    @ApiModelProperty(value = "更新者")
    @ExcelExport("更新者")
    private String updateBy;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建时间")
    @ExcelExport("创建时间")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    @TableField(value = "project_id")
    @ApiModelProperty(value = "项目ID")
    @ExcelExport("项目ID")
    private Long projectId;

    @TableField(value = "type_databese")
    @ApiModelProperty(value = "类型")
    @ExcelExport("类型")
    private String typeDatabese;

    private static final long serialVersionUID = 1L;

    public static final String COL_DB_ID = "db_id";

    public static final String COL_NAME = "name";

    public static final String COL_JDBC_URL = "jdbc_url";

    public static final String COL_USER_NAME = "user_name";

    public static final String COL_PWD = "pwd";

    public static final String COL_CREATE_BY = "create_by";

    public static final String COL_UPDATE_BY = "update_by";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

    public static final String COL_PROJECT_ID = "project_id";

    public static final String COL_TYPE_DATABESE = "type_databese";

}