package fun.yizhierha.operation.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:42:52 CST 2022
**/
@ApiModel(value = "部署管理")
@Data
@TableName(value = "ora_deploy")
public class OraDeploy implements Serializable{

    @TableId(value = "deploy_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "app_id")
    @ApiModelProperty(value = "应用编号")
    @ExcelExport("应用编号")
    private Long appId;

    @TableField(value = "create_by")
    @ApiModelProperty(value = "创建者")
    @ExcelExport("创建者")
    private String createBy;

    @TableField(value = "update_by")
    @ApiModelProperty(value = "更新者")
    @ExcelExport("更新者")
    private String updateBy;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建时间")
    @ExcelExport("创建时间")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    @TableField(value = "project_id")
    @ApiModelProperty(value = "项目ID")
    @ExcelExport("项目ID")
    private Long projectId;

    @TableField(value = "server_id")
    @ApiModelProperty(value = "服务器")
    @ExcelExport("服务器")
    private Long serverId;

    private static final long serialVersionUID = 1L;

    public static final String COL_DEPLOY_ID = "deploy_id";

    public static final String COL_APP_ID = "app_id";

    public static final String COL_CREATE_BY = "create_by";

    public static final String COL_UPDATE_BY = "update_by";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

    public static final String COL_PROJECT_ID = "project_id";

    public static final String COL_SERVER_ID = "server_id";

}