package fun.yizhierha.operation.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 00:05:47 CST 2022
**/
@ApiModel(value = "项目管理")
@Data
@TableName(value = "ora_project")
public class OraProject implements Serializable{

    @TableId(value = "project_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "pname")
    @ApiModelProperty(value = "项目名称")
    @ExcelExport("项目名称")
    private String pname;

    @TableField(value = "plan_start_date")
    @ApiModelProperty(value = "项目计划开始日期")
    @ExcelExport("项目计划开始日期")
    private Timestamp planStartDate;

    @TableField(value = "plan_finish_date")
    @ApiModelProperty(value = "项目计划结束日期")
    @ExcelExport("项目计划结束日期")
    private Timestamp planFinishDate;

    @TableField(value = "create_by")
    @ApiModelProperty(value = "创建者")
    @ExcelExport("创建者")
    private String createBy;

    @TableField(value = "update_by")
    @ApiModelProperty(value = "更新者")
    @ExcelExport("更新者")
    private String updateBy;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建时间")
    @ExcelExport("创建时间")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    @TableField(value = "actu_start_date")
    @ApiModelProperty(value = "实际开始日期")
    @ExcelExport("实际开始日期")
    private Timestamp actuStartDate;

    @TableField(value = "actu_finish_date")
    @ApiModelProperty(value = "实际结束日期")
    @ExcelExport("实际结束日期")
    private Timestamp actuFinishDate;

    @TableField(value = "enabled")
    @ApiModelProperty(value = "状态：1启用、0禁用")
    @ExcelExport("状态：1启用、0禁用")
    private Boolean enabled;

    private static final long serialVersionUID = 1L;

    public static final String COL_PROJECT_ID = "project_id";

    public static final String COL_PNAME = "pname";

    public static final String COL_PLAN_START_DATE = "plan_start_date";

    public static final String COL_PLAN_FINISH_DATE = "plan_finish_date";

    public static final String COL_CREATE_BY = "create_by";

    public static final String COL_UPDATE_BY = "update_by";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

    public static final String COL_ACTU_START_DATE = "actu_start_date";

    public static final String COL_ACTU_FINISH_DATE = "actu_finish_date";

    public static final String COL_ENABLED = "enabled";

}