package fun.yizhierha.operation.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 13:25:19 CST 2022
**/
@ApiModel(value = "服务器")
@Data
@TableName(value = "ora_server")
public class OraServer implements Serializable{

    @TableId(value = "server_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "account")
    @ApiModelProperty(value = "账号")
    @ExcelExport("账号")
    private String account;

    @TableField(value = "ip")
    @ApiModelProperty(value = "IP地址")
    @ExcelExport("IP地址")
    private String ip;

    @TableField(value = "name")
    @ApiModelProperty(value = "名称")
    @ExcelExport("名称")
    private String name;

    @TableField(value = "password")
    @ApiModelProperty(value = "密码")
    @ExcelExport("密码")
    private String password;

    @TableField(value = "port")
    @ApiModelProperty(value = "端口")
    @ExcelExport("端口")
    private Integer port;

    @TableField(value = "create_by")
    @ApiModelProperty(value = "创建者")
    @ExcelExport("创建者")
    private String createBy;

    @TableField(value = "update_by")
    @ApiModelProperty(value = "更新者")
    @ExcelExport("更新者")
    private String updateBy;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建时间")
    @ExcelExport("创建时间")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    @TableField(value = "project_id")
    @ApiModelProperty(value = "项目ID")
    @ExcelExport("项目ID")
    private Long projectId;
    @TableField(exist = false)
    private OraProject project;

    private static final long serialVersionUID = 1L;

    public static final String COL_SERVER_ID = "server_id";

    public static final String COL_ACCOUNT = "account";

    public static final String COL_IP = "ip";

    public static final String COL_NAME = "name";

    public static final String COL_PASSWORD = "password";

    public static final String COL_PORT = "port";

    public static final String COL_CREATE_BY = "create_by";

    public static final String COL_UPDATE_BY = "update_by";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

    public static final String COL_PROJECT_ID = "project_id";

}