package fun.yizhierha.operation.controller;

import fun.yizhierha.common.annotation.Log;
import fun.yizhierha.common.base.BaseErrDto;
import fun.yizhierha.common.exception.BizCodeEnum;
import fun.yizhierha.common.utils.ValidUtils;
import fun.yizhierha.common.utils.*;
import fun.yizhierha.operation.domain.OraDeploy;
import fun.yizhierha.operation.domain.vo.CreateOraDeployVo;
import fun.yizhierha.operation.domain.vo.UpdateOraDeployVo;
import fun.yizhierha.operation.domain.vo.RetrieveOraDeployVo;

import fun.yizhierha.operation.service.OraDeployService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import lombok.RequiredArgsConstructor;

import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.Set;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:42:52 CST 2022
**/
@Api(tags = "运维管理:部署管理")
@RestController
@RequestMapping("/api/operation/deploy")
@RequiredArgsConstructor
public class OraDeployController{

    private final OraDeployService oraDeployService;

    @ApiOperation("获取部署管理")
    @Log("获取部署管理")
    @GetMapping
    @PreAuthorize("@eh.check('operation:oraDeploy:list')")
    public R<PageUtils<OraDeploy>> list(RetrieveOraDeployVo retrieveOraDeployVo, Query.PageVo pageVo){
        PageUtils<OraDeploy> res = oraDeployService.list(retrieveOraDeployVo,pageVo);
        return R.<PageUtils<OraDeploy>>ok().setData(res);
    }

    @ApiOperation("新增部署管理")
    @Log("新增部署管理")
    @PostMapping
    @PreAuthorize("@eh.check('operation:oraDeploy:add')")
    public R<List<BaseErrDto>> add(@Validated @RequestBody CreateOraDeployVo createOraDeployVo,
        BindingResult bindingResult){
        List<BaseErrDto> errDtoList = ValidUtils.getBaseErrDtoByBindingRes(bindingResult);
        if (errDtoList.isEmpty()){
            oraDeployService.save(createOraDeployVo);
            return R.ok();
        }
        return R.<List<BaseErrDto>>error(
                BizCodeEnum.Client_Error_CRUD.getCode(), BizCodeEnum.Client_Error_CRUD.getMsg()
        ).setData(errDtoList);
    }

    @ApiOperation("修改部署管理")
    @Log("修改部署管理")
    @PutMapping
    @PreAuthorize("@eh.check('operation:oraDeploy:edit')")
    public R<List<BaseErrDto>> edit(@Validated @RequestBody ValidList<UpdateOraDeployVo> updateOraDeployList,
                    BindingResult bindingResult){
        List<BaseErrDto> errDtoList = ValidUtils.getBaseErrDtoByBindingRes(updateOraDeployList, bindingResult);
        if (errDtoList.isEmpty()) {
            oraDeployService.edit(updateOraDeployList,errDtoList);
            if (errDtoList.isEmpty()){
                return R.ok();
            }else {
                return  R.<List<BaseErrDto>>error(
                        BizCodeEnum.Client_Error_CRUD.getCode(),
                        BizCodeEnum.Client_Error_CRUD.getMsg()
                ).setData(errDtoList);
            }
        }
        return  R.<List<BaseErrDto>>error(
                BizCodeEnum.Client_Error_CRUD.getCode(),
                BizCodeEnum.Client_Error_CRUD.getMsg()
        ).setData(errDtoList);
    }

    @ApiOperation("删除部署管理")
    @Log("删除部署管理")
    @DeleteMapping
    @PreAuthorize("@eh.check('operation:oraDeploy:del')")
    public R del(@RequestBody Set<Long> ids){
        oraDeployService.remove(ids);
        return R.ok();
    }

    @ApiOperation("导出数据")
    @Log("导出数据")
    @GetMapping("/download")
    @PreAuthorize("@eh.check('operation:oraDeploy:list')")
    public void download(HttpServletResponse response){
        oraDeployService.download(response);
    }

}