package fun.yizhierha.tools.other.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.tools.other.domain.ToolQiniuContent;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author erha
* @date Sun Jan 08 14:05:28 CST 2023
**/
@Mapper
public interface ToolQiniuContentMapper extends BaseMapper<ToolQiniuContent>{
}