package fun.yizhierha.tools.other.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.tools.other.domain.ToolEmailConfig;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author 二哈
* @date Fri Jan 13 20:37:24 CST 2023
**/
@Mapper
public interface ToolEmailConfigMapper extends BaseMapper<ToolEmailConfig>{
}