package fun.yizhierha.tools.other.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.tools.other.domain.ToolLocalStorage;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author erha
* @date Sun Jan 01 17:11:43 CST 2023
**/
@Mapper
public interface ToolLocalStorageMapper extends BaseMapper<ToolLocalStorage>{
}