package fun.yizhierha.tools.other.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.tools.other.domain.ToolQiniuConfig;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author erha
* @date Sun Jan 08 13:57:58 CST 2023
**/
@Mapper
public interface ToolQiniuConfigMapper extends BaseMapper<ToolQiniuConfig>{
}