package fun.yizhierha.tools.other.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author erha
* @date Sun Jan 08 14:05:28 CST 2023
**/
@ApiModel(value = "七牛云")
@Data
@TableName(value = "tool_qiniu_content")
public class ToolQiniuContent implements Serializable{

    @TableId(value = "content_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "bucket")
    @ApiModelProperty(value = "Bucket 识别符")
    @ExcelExport("Bucket 识别符")
    private String bucket;

    @TableField(value = "name")
    @ApiModelProperty(value = "文件名称")
    @ExcelExport("文件名称")
    private String name;

    @TableField(value = "size")
    @ApiModelProperty(value = "文件大小")
    @ExcelExport("文件大小")
    private String size;

    @TableField(value = "type")
    @ApiModelProperty(value = "文件类型：私有或公开")
    @ExcelExport("文件类型：私有或公开")
    private String type;

    @TableField(value = "url")
    @ApiModelProperty(value = "文件url")
    @ExcelExport("文件url")
    private String url;

    @TableField(value = "suffix")
    @ApiModelProperty(value = "文件后缀")
    @ExcelExport("文件后缀")
    private String suffix;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "上传或同步的时间")
    @ExcelExport("上传或同步的时间")
    private Timestamp updateTime;

    private static final long serialVersionUID = 1L;

    public static final String COL_CONTENT_ID = "content_id";

    public static final String COL_BUCKET = "bucket";

    public static final String COL_NAME = "name";

    public static final String COL_SIZE = "size";

    public static final String COL_TYPE = "type";

    public static final String COL_URL = "url";

    public static final String COL_SUFFIX = "suffix";

    public static final String COL_UPDATE_TIME = "update_time";

}