package fun.yizhierha.tools.other.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author erha
* @date Sun Jan 01 17:11:43 CST 2023
**/
@ApiModel(value = "存储管理")
@Data
@TableName(value = "tool_local_storage")
public class ToolLocalStorage implements Serializable{

    @TableId(value = "storage_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "real_name")
    @ApiModelProperty(value = "文件真实的名称")
    @ExcelExport("文件真实的名称")
    private String realName;

    @TableField(value = "name")
    @ApiModelProperty(value = "文件名")
    @ExcelExport("文件名")
    private String name;

    @TableField(value = "suffix")
    @ApiModelProperty(value = "后缀")
    @ExcelExport("后缀")
    private String suffix;

    @TableField(value = "path")
    @ApiModelProperty(value = "路径")
    @ExcelExport("路径")
    private String path;

    @TableField(value = "type")
    @ApiModelProperty(value = "类型")
    @ExcelExport("类型")
    private String type;

    @TableField(value = "size")
    @ApiModelProperty(value = "大小")
    @ExcelExport("大小")
    private String size;

    @TableField(value = "bit_size")
    @ApiModelProperty(value = "bit大小")
    @ExcelExport("bit大小")
    private Long bitSize;

    @TableField(value = "create_by")
    @ApiModelProperty(value = "创建者")
    @ExcelExport("创建者")
    private String createBy;

    @TableField(value = "update_by")
    @ApiModelProperty(value = "更新者")
    @ExcelExport("更新者")
    private String updateBy;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建日期")
    @ExcelExport("创建日期")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    private static final long serialVersionUID = 1L;

    public static final String COL_STORAGE_ID = "storage_id";

    public static final String COL_REAL_NAME = "real_name";

    public static final String COL_NAME = "name";

    public static final String COL_SUFFIX = "suffix";

    public static final String COL_PATH = "path";

    public static final String COL_TYPE = "type";

    public static final String COL_SIZE = "size";
    public static final String COL_BIT_SIZE = "bit_size";

    public static final String COL_CREATE_BY = "create_by";

    public static final String COL_UPDATE_BY = "update_by";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

}