package fun.yizhierha.tools.other.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;


/** generated by EH-Admin
* @author 二哈
* @date Fri Jan 13 20:37:24 CST 2023
**/
@ApiModel(value = "邮件配置")
@Data
@TableName(value = "tool_email_config")
public class ToolEmailConfig implements Serializable{

    @TableId(value = "config_id", type = IdType.INPUT)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "from_user")
    @ApiModelProperty(value = "收件人")
    @ExcelExport("收件人")
    private String fromUser;

    @TableField(value = "host")
    @ApiModelProperty(value = "邮件服务器SMTP地址")
    @ExcelExport("邮件服务器SMTP地址")
    private String host;

    @TableField(value = "pass")
    @ApiModelProperty(value = "密码")
    @ExcelExport("密码")
    private String pass;

    @TableField(value = "port")
    @ApiModelProperty(value = "端口")
    @ExcelExport("端口")
    private String port;

    @TableField(value = "user")
    @ApiModelProperty(value = "发件者用户名")
    @ExcelExport("发件者用户名")
    private String user;

    @TableField(value = "active")
    @ApiModelProperty(value = "是否激活")
    @ExcelExport("是否激活")
    private Boolean active;

    private static final long serialVersionUID = 1L;

    public static final String COL_CONFIG_ID = "config_id";

    public static final String COL_FROM_USER = "from_user";

    public static final String COL_HOST = "host";

    public static final String COL_PASS = "pass";

    public static final String COL_PORT = "port";

    public static final String COL_USER = "user";

    public static final String COL_ACTIVE = "active";

}