package fun.yizhierha.operation.service;

import fun.yizhierha.common.base.BaseErrDto;
import fun.yizhierha.common.utils.PageUtils;
import fun.yizhierha.common.utils.Query;
import fun.yizhierha.common.utils.ValidList;
import com.baomidou.mybatisplus.extension.service.IService;
import fun.yizhierha.operation.domain.OraApp;
import fun.yizhierha.operation.domain.vo.CreateOraAppVo;
import fun.yizhierha.operation.domain.vo.UpdateOraAppVo;
import fun.yizhierha.operation.domain.vo.RetrieveOraAppVo;

import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.Set;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:15:54 CST 2022
**/
public interface OraAppService extends IService<OraApp>{

    PageUtils<OraApp> list(RetrieveOraAppVo retrieveOraAppVo, Query.PageVo pageVo);

    void save(CreateOraAppVo createOraAppVo);

    void edit(ValidList<UpdateOraAppVo> updateOraAppVoList, List<BaseErrDto> errDtoList);

    void remove(Set<Long> ids);

    void download(HttpServletResponse response);

}