package fun.yizhierha.operation.service;

import fun.yizhierha.common.base.BaseErrDto;
import fun.yizhierha.common.utils.PageUtils;
import fun.yizhierha.common.utils.Query;
import fun.yizhierha.common.utils.ValidList;
import com.baomidou.mybatisplus.extension.service.IService;
import fun.yizhierha.operation.domain.OraDeploy;
import fun.yizhierha.operation.domain.OraDeployHistory;
import fun.yizhierha.operation.domain.vo.CreateOraDeployVo;
import fun.yizhierha.operation.domain.vo.UpdateOraDeployVo;
import fun.yizhierha.operation.domain.vo.RetrieveOraDeployVo;

import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.Set;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:42:52 CST 2022
**/
public interface OraDeployService extends IService<OraDeploy>{

    PageUtils<OraDeploy> list(RetrieveOraDeployVo retrieveOraDeployVo, Query.PageVo pageVo);

    void save(CreateOraDeployVo createOraDeployVo);

    void edit(ValidList<UpdateOraDeployVo> updateOraDeployVoList, List<BaseErrDto> errDtoList);

    void remove(Set<Long> ids);

    void download(HttpServletResponse response);

    void deploy(String dir, Long id);

    String serverReduction(Long deployHisId);

    String serverStatus(Long deployId);

    String startServer(Long deployId);

    String stopServer(Long deployId);
}