package fun.yizhierha.operation.service;

import fun.yizhierha.common.base.BaseErrDto;
import fun.yizhierha.common.utils.PageUtils;
import fun.yizhierha.common.utils.Query;
import fun.yizhierha.common.utils.ValidList;
import com.baomidou.mybatisplus.extension.service.IService;
import fun.yizhierha.operation.domain.OraServer;
import fun.yizhierha.operation.domain.vo.CreateOraServerVo;
import fun.yizhierha.operation.domain.vo.UpdateOraServerVo;
import fun.yizhierha.operation.domain.vo.RetrieveOraServerVo;

import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.Set;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 13:25:19 CST 2022
**/
public interface OraServerService extends IService<OraServer>{

    PageUtils<OraServer> list(RetrieveOraServerVo retrieveOraServerVo, Query.PageVo pageVo);

    void save(CreateOraServerVo createOraServerVo);

    void edit(ValidList<UpdateOraServerVo> updateOraServerVoList, List<BaseErrDto> errDtoList);

    void remove(Set<Long> ids);

    void download(HttpServletResponse response);

    OraServer findByIp(String ip);

    Boolean testConnect(CreateOraServerVo createOraServerVo);
}