package fun.yizhierha.test.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.test.domain.TestStudent;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author 二哈
* @date Sat Nov 26 15:55:33 CST 2022
**/
@Mapper
public interface TestStudentMapper extends BaseMapper<TestStudent>{
}