package fun.yizhierha.operation.service.mapstruct;

import fun.yizhierha.operation.domain.vo.CreateOraAppVo;
import fun.yizhierha.operation.domain.vo.UpdateOraAppVo;
import org.mapstruct.Mapper;
import fun.yizhierha.operation.domain.OraApp;


/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:15:54 CST 2022
**/
@Mapper(componentModel = "spring")
public interface OraAppMapstruct{

    OraApp toOraApp(UpdateOraAppVo updateOraAppVo);

    OraApp toOraApp(CreateOraAppVo createOraAppVo);

}