package fun.yizhierha.operation.service.mapstruct;

import fun.yizhierha.operation.domain.vo.CreateOraDeployVo;
import fun.yizhierha.operation.domain.vo.UpdateOraDeployVo;
import org.mapstruct.Mapper;
import fun.yizhierha.operation.domain.OraDeploy;


/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:42:52 CST 2022
**/
@Mapper(componentModel = "spring")
public interface OraDeployMapstruct{

    OraDeploy toOraDeploy(UpdateOraDeployVo updateOraDeployVo);

    OraDeploy toOraDeploy(CreateOraDeployVo createOraDeployVo);

}