package fun.yizhierha.operation.service.mapstruct;

import fun.yizhierha.operation.domain.vo.CreateOraProjectVo;
import fun.yizhierha.operation.domain.vo.UpdateOraProjectVo;
import org.mapstruct.Mapper;
import fun.yizhierha.operation.domain.OraProject;


/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 00:05:47 CST 2022
**/
@Mapper(componentModel = "spring")
public interface OraProjectMapstruct{

    OraProject toOraProject(UpdateOraProjectVo updateOraProjectVo);

    OraProject toOraProject(CreateOraProjectVo createOraProjectVo);

}