package fun.yizhierha.test.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.math.BigDecimal;
import java.sql.Timestamp;

/** generated by EH-Admin
 * @author 二哈
 * @date Tue Nov 29 22:10:18 CST 2022
 **/
@ApiModel(value = "学生")
@Data
@TableName(value = "test_student")
public class TestStudent implements Serializable{

    @TableId(value = "student_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "name")
    @ApiModelProperty(value = "学生姓名")
    @ExcelExport("学生姓名")
    private String name;

    @TableField(value = "like_food")
    @ApiModelProperty(value = "水果")
    @ExcelExport("水果")
    private String likeFood;

    @TableField(value = "age")
    @ApiModelProperty(value = "年龄")
    @ExcelExport("年龄")
    private Integer age;

    @TableField(value = "clazz_name")
    @ApiModelProperty(value = "班级名")
    @ExcelExport("班级名")
    private String clazzName;

    @TableField(value = "gender")
    @ApiModelProperty(value = "性别")
    @ExcelExport("性别")
    private Boolean gender;

    @TableField(value = "avg_score")
    @ApiModelProperty(value = "综合评分")
    @ExcelExport("综合评分")
    private BigDecimal avgScore;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建时间")
    @ExcelExport("创建时间")
    private Timestamp createTime;

    @TableField(value = "update_time")
    @ApiModelProperty(value = "更新时间")
    @ExcelExport("更新时间")
    private Timestamp updateTime;

    @TableField(value = "enabled")
    @ApiModelProperty(value = "状态")
    @ExcelExport("状态")
    private Boolean enabled;

    @TableField(value = "expire_time")
    @ApiModelProperty(value = "账号过期时间")
    @ExcelExport("账号过期时间")
    private Timestamp expireTime;

    private static final long serialVersionUID = 1L;

    public static final String COL_STUDENT_ID = "student_id";

    public static final String COL_NAME = "name";

    public static final String COL_LIKE_FOOD = "like_food";

    public static final String COL_AGE = "age";

    public static final String COL_CLAZZ_NAME = "clazz_name";

    public static final String COL_GENDER = "gender";

    public static final String COL_AVG_SCORE = "avg_score";

    public static final String COL_CREATE_TIME = "create_time";

    public static final String COL_UPDATE_TIME = "update_time";

    public static final String COL_ENABLED = "enabled";

    public static final String COL_EXPIRE_TIME = "expire_time";

}