package fun.yizhierha.monitor.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import fun.yizhierha.common.utils.file.ExcelExport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.Data;

import java.sql.Timestamp;

/** generated by EH-Admin
* @author 二哈
* @date Fri Dec 09 20:47:12 CST 2022
**/
@ApiModel(value = "操作日志")
@Data
@TableName(value = "sys_log")
public class SysLog implements Serializable{

    @TableId(value = "log_id", type = IdType.AUTO)
    @ApiModelProperty(value = "ID")
    @ExcelExport("id")
    private Long id;

    @TableField(value = "description")
    @ApiModelProperty(value = "描述")
    @ExcelExport("描述")
    private String description;

    @TableField(value = "log_type")
    @ApiModelProperty(value = "日志类型")
    @ExcelExport("日志类型")
    private String logType;

    @TableField(value = "method")
    @ApiModelProperty(value = "执行方法")
    @ExcelExport("执行方法")
    private String method;

    @TableField(value = "params")
    @ApiModelProperty(value = "参数")
    @ExcelExport("参数")
    private String params;

    @TableField(value = "request_ip")
    @ApiModelProperty(value = "IP来源")
    @ExcelExport("IP来源")
    private String requestIp;

    @TableField(value = "time")
    @ApiModelProperty(value = "耗时")
    @ExcelExport("耗时")
    private Long time;

    @TableField(value = "username")
    @ApiModelProperty(value = "用户名")
    @ExcelExport("用户名")
    private String username;

    @TableField(value = "address")
    @ApiModelProperty(value = "IP归属地")
    @ExcelExport("IP归属地")
    private String address;

    @TableField(value = "browser")
    @ApiModelProperty(value = "浏览器")
    @ExcelExport("浏览器")
    private String browser;

    @TableField(value = "exception_detail")
    @ApiModelProperty(value = "异常信息")
    @ExcelExport("异常信息")
    private String exceptionDetail;

    @TableField(value = "create_time")
    @ApiModelProperty(value = "创建时间")
    @ExcelExport("创建时间")
    private Timestamp createTime;

    private static final long serialVersionUID = 1L;

    public static final String COL_LOG_ID = "log_id";

    public static final String COL_DESCRIPTION = "description";

    public static final String COL_LOG_TYPE = "log_type";

    public static final String COL_METHOD = "method";

    public static final String COL_PARAMS = "params";

    public static final String COL_REQUEST_IP = "request_ip";

    public static final String COL_TIME = "time";

    public static final String COL_USERNAME = "username";

    public static final String COL_ADDRESS = "address";

    public static final String COL_BROWSER = "browser";

    public static final String COL_EXCEPTION_DETAIL = "exception_detail";

    public static final String COL_CREATE_TIME = "create_time";

}