package fun.yizhierha.monitor.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.monitor.domain.SysLog;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author 二哈
* @date Fri Dec 09 20:47:12 CST 2022
**/
@Mapper
public interface SysLogMapper extends BaseMapper<SysLog>{
}