#异步任务线程池
task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50


#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/秒
  token-validity-in-minutes: 100
  # 在线用户key
  online-key: eh-online-token-
  # 验证码
  code-key: eh-captcha-code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000
# IP 本地解析
ip:
  local-parsing: true
# 登录相关配置
login:
  # 登录缓存
  cache-enable: true
  #  是否限制单用户登录
  single-login: false
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25


# 内存用户缓存配置
user-cache:
  # 最小回收数(当缓存数量达到此值时进行回收)
  min-evictable-size: 512
  # 最小回收间隔
  min-evictable-interval: 1800000
  # 最小存活时间 (ms)
  min-idle-time: 3600000


# rsa前端公钥加密，后端私钥解密
rsa:
  privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBALFIwpV+4qaIlJCHCo0oeJnmXzKv8lkdghaexgY0YM8PuAhT+h+JyKF6T8VVAjr0jAkT0/vOlrIJur/PqeiYHQLjQne9WELuW9ayvz5YM5BN0oN/hZqXhdz2c3QlsYUDWpsPnYa2ttywv2DOIZqqgCHDLSX/nUhP0jkmIfCzTK3PAgMBAAECgYBy9AnwI8FVWJR0jovB8e8ZY65w0HOlYyPaBQPEPCxVtwyOod06m/3y7rtQ6gkzLySqMigvS8qdEP/9peq3PgL4qxH1fldVT91R+5siI0hShrTPa7rsuTYqrQi/vmFEwKk40iyz9Nbwn5GTSAWXrFm2OMm87QcgZms3vBDNmysN2QJBANh06adT75f4Lu3J0af55WynR0Ne6KyIWbAXHPvhPHBbP093HSE/GLx/prUbDO2kMH4Ej6f0CZgHZ6j/oDMPaLUCQQDRq9uqEdJpWxVydL+V3c+iHf/Qi0wKjUtBFkF+TbBzWKcchcZ8hBzCpnJ3SaEeOHcdGPx5BeUrndcmXqYwm2LzAkBsuNybtWdE993qhlKOgtCf8K20wzkvYBVcg1+FjK6k6NA2A+hXyK+ODrgXg4zM2Ima4oOdotAm0qFYm31F6Fl5AkAHgWlpmx23G8WWxUseaERIf15q7rGYJxqsh8lsZgeM+X1x7e//AROufBrY3k/gLxFEf2J6SpW7i/jprLWyQ721AkBoS8uG9Jin5SVb68ye0fPFf0QO+VdIxwwPt7Kw32itQg1JJXWz90Fz88kuGcow4Q+uCf3vmccEy/4VGc8/OSiL

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/ehadmin/file/
    avatar: /home/ehadmin/avatar/
  windows:
    path: C:\ehadmin\file\
    avatar: C:\ehadmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
