package fun.yizhierha.tools.other.service.mapstruct;

import fun.yizhierha.tools.other.domain.vo.CreateToolQiniuContentVo;
import fun.yizhierha.tools.other.domain.vo.UpdateToolQiniuContentVo;
import org.mapstruct.Mapper;
import fun.yizhierha.tools.other.domain.ToolQiniuContent;


/** generated by EH-Admin
* @author erha
* @date Sun Jan 08 14:05:28 CST 2023
**/
@Mapper(componentModel = "spring")
public interface ToolQiniuContentMapstruct{

    ToolQiniuContent toToolQiniuContent(UpdateToolQiniuContentVo updateToolQiniuContentVo);

    ToolQiniuContent toToolQiniuContent(CreateToolQiniuContentVo createToolQiniuContentVo);

}