package fun.yizhierha.tools.other.service.mapstruct;

import fun.yizhierha.tools.other.domain.vo.CreateToolEmailConfigVo;
import fun.yizhierha.tools.other.domain.vo.UpdateToolEmailConfigVo;
import org.mapstruct.Mapper;
import fun.yizhierha.tools.other.domain.ToolEmailConfig;


/** generated by EH-Admin
* @author 二哈
* @date Fri Jan 13 20:37:24 CST 2023
**/
@Mapper(componentModel = "spring")
public interface ToolEmailConfigMapstruct{

    ToolEmailConfig toToolEmailConfig(UpdateToolEmailConfigVo updateToolEmailConfigVo);

    ToolEmailConfig toToolEmailConfig(CreateToolEmailConfigVo createToolEmailConfigVo);

}