package fun.yizhierha.tools.other.service.mapstruct;

import fun.yizhierha.tools.other.domain.vo.CreateToolLocalStorageVo;
import fun.yizhierha.tools.other.domain.vo.UpdateToolLocalStorageVo;
import org.mapstruct.Mapper;
import fun.yizhierha.tools.other.domain.ToolLocalStorage;


/** generated by EH-Admin
* @author erha
* @date Sun Jan 01 17:11:43 CST 2023
**/
@Mapper(componentModel = "spring")
public interface ToolLocalStorageMapstruct{

    ToolLocalStorage toToolLocalStorage(UpdateToolLocalStorageVo updateToolLocalStorageVo);

    ToolLocalStorage toToolLocalStorage(CreateToolLocalStorageVo createToolLocalStorageVo);

}