package ${package}.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import ${package}.domain.${className};
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author ${author}
* @date ${date}
**/
@Mapper
public interface ${className}Mapper extends BaseMapper<${className}>{
}