package ${package}.service.mapstruct;

import ${package}.domain.vo.Create${className}Vo;
import ${package}.domain.vo.Update${className}Vo;
import org.mapstruct.Mapper;
import ${package}.domain.${className};
<#list columns as col>
    <#if col.formType == '下拉框[多选]' && col.formShow>
import org.mapstruct.Mapping;
        <#break >
    </#if>
</#list>


/** generated by EH-Admin
* @author ${author}
* @date ${date}
**/
@Mapper(componentModel = "spring")
public interface ${className}Mapstruct{

<#list columns as col>
    <#if col.formType == '下拉框[多选]' && col.formShow>
    @Mapping(target = "${col.changeColumnName}", expression = "java(fun.yizhierha.common.utils.ArrayUtils.toString(update${className}Vo.get${col.capitalColumnName}()))")
    </#if>
</#list>
    ${className} to${className}(Update${className}Vo update${className}Vo);

<#list columns as col>
    <#if col.formType == '下拉框[多选]' && col.formShow>
    @Mapping(target = "${col.changeColumnName}", expression = "java(fun.yizhierha.common.utils.ArrayUtils.toString(create${className}Vo.get${col.capitalColumnName}()))")
    </#if>
</#list>
    ${className} to${className}(Create${className}Vo create${className}Vo);

}