package fun.yizhierha.test.service.mapstruct;

import fun.yizhierha.test.domain.vo.CreateTestStudentVo;
import fun.yizhierha.test.domain.vo.UpdateTestStudentVo;
import org.mapstruct.Mapper;
import fun.yizhierha.test.domain.TestStudent;
import org.mapstruct.Mapping;

/** generated by EH-Admin
 * @author 二哈
 * @date Tue Nov 29 22:10:18 CST 2022
 **/
@Mapper(componentModel = "spring")
public interface TestStudentMapstruct{

    @Mapping(target = "likeFood", expression = "java(fun.yizhierha.common.utils.ArrayUtils.toString(updateTestStudentVo.getLikeFood()))")
    TestStudent toTestStudent(UpdateTestStudentVo updateTestStudentVo);

    @Mapping(target = "likeFood", expression = "java(fun.yizhierha.common.utils.ArrayUtils.toString(createTestStudentVo.getLikeFood()))")
    TestStudent toTestStudent(CreateTestStudentVo createTestStudentVo);

}