package fun.yizhierha.monitor.service;

import fun.yizhierha.common.utils.PageUtils;
import fun.yizhierha.common.utils.Query;
import fun.yizhierha.monitor.domain.vo.RetrieveOnlineUserVo;
import fun.yizhierha.monitor.service.dto.OnlineUserDto;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Collection;
import java.util.List;
import java.util.Set;

/** generated by EH-Admin
* @author 二哈
* @date Fri Dec 02 10:41:49 CST 2022
**/
public interface OnlineUserService {


    OnlineUserDto getByToken(String token);

    void save(String deptName,
         String username,
         String nickName,
         String token, HttpServletRequest request);

    void removeIfExist(String username);

    void logout(String token);

    void removeIfExist(Collection<String> usernames);

    void download(HttpServletResponse response);

    PageUtils<OnlineUserDto> list(RetrieveOnlineUserVo retrieveOnlineUserVo, Query.PageVo pageVo);

    List<OnlineUserDto> list();
}