package fun.yizhierha.monitor.service;

import fun.yizhierha.common.utils.PageUtils;
import fun.yizhierha.common.utils.Query;
import com.baomidou.mybatisplus.extension.service.IService;
import fun.yizhierha.monitor.domain.SysLog;
import fun.yizhierha.monitor.domain.vo.RetrieveSysLogVo;
import org.aspectj.lang.ProceedingJoinPoint;

import javax.servlet.http.HttpServletResponse;
import java.util.Set;

/** generated by EH-Admin
* @author 二哈
* @date Fri Dec 09 20:47:12 CST 2022
**/
public interface SysLogService extends IService<SysLog>{

    PageUtils<SysLog> list(RetrieveSysLogVo retrieveSysLogVo, Query.PageVo pageVo);


    void remove(Set<Long> ids);

    void download(HttpServletResponse response);

    void save(String username, String browserByRequest, String ipByRequest, ProceedingJoinPoint joinPoint, SysLog log);
}