package fun.yizhierha.operation.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.operation.domain.OraApp;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:15:54 CST 2022
**/
@Mapper
public interface OraAppMapper extends BaseMapper<OraApp>{
}