package fun.yizhierha.operation.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.operation.domain.OraDatabase;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 16:08:00 CST 2022
**/
@Mapper
public interface OraDatabaseMapper extends BaseMapper<OraDatabase>{
}