package fun.yizhierha.operation.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import fun.yizhierha.operation.domain.OraDeploy;
import fun.yizhierha.operation.domain.OraDeployServer;
import fun.yizhierha.operation.domain.vo.RetrieveOraDeployVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:42:52 CST 2022
**/
@Mapper
public interface OraDeployMapper extends BaseMapper<OraDeploy>{
    IPage<OraDeploy> selectByRtVo(IPage<OraDeploy> page, @Param("vo") RetrieveOraDeployVo retrieveOraDeployVo);
}