package fun.yizhierha.operation.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.operation.domain.OraDeployHistory;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 15:55:14 CST 2022
**/
@Mapper
public interface OraDeployHistoryMapper extends BaseMapper<OraDeployHistory>{
}