package fun.yizhierha.operation.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import fun.yizhierha.operation.domain.OraProject;
import org.apache.ibatis.annotations.Mapper;

/** generated by EH-Admin
* @author xaopohi
* @date Wed Dec 21 00:05:47 CST 2022
**/
@Mapper
public interface OraProjectMapper extends BaseMapper<OraProject>{
}